### ISSUE TITLE
Can't use OCR.WordsBoundingRect

### ISSUE THREAD

**Issue by MatejGolian** [Descolada/OCR#3]
For some reason OCR.WordsBoundingRect gives me an error. If I understand correctly, the code example below should work, and yet it doesn't:

`#Requires AutoHotkey v2.0

#Include OCR.ahk

^+O:: {
    OCRResult := OCR.FromWindow("A")
    For OCRLine In OCRResult.Lines
    MsgBox OCR.WordsBoundingRect(OCRLine.Words).W . ", " . OCR.WordsBoundingRect(OCRLine.Words).H
}`

It produces the following error:

> Error: This value of type "Array" has no property named "x".
> 
> 	---- C:\OCR.ahk
> 	722: For word in words
> 	722: {
> ▶	723: X1 := Min(word.x, X1), Y1 := Min(word.y, Y1), X2 := Max(word.x+word.w, X2), Y2 := Max(word.y+word.h, Y2)
> 	724: }
> 	725: Return {X:X1, Y:Y1, W:X2-X1, H:Y2-Y1, X2:X2, Y2:Y2}

The strange thing is that everything seems OK to me, even your code, so where is the problem? Is there something that I still don't understand?

Many thanks. 🙂

**Comment by Descolada** [comment]
OCR.WordsBoundingRect expects a number of OCR.Word arguments, not an array of Words. This means you can spread OCRLine.Words with *: `OCR.WordsBoundingRect(OCRLine.Words*)`

**Comment by MatejGolian** [comment]
Thank you for the clarification. It works beautifully.
And thanks for making this great library. 👍
