### ISSUE TITLE
Single character recognition

### ISSUE THREAD

**Issue by ktwb** [Descolada/OCR#4]
Unsure if this one is a UWP OCR feature or whether there is a way to change this, but currently this will only OCR if there is a run of 2 or more characters for it to detect.

While I appreciate this is a false-positive prevention feature that is doing significant work, is there some way to turn it off if it's coming from the code, or to ask the UWP OCR to do a single-character recognition?

Apologies if this isn't the place to ask - I'm not really experienced with Github and I couldn't find anywhere else that would allow me to ask!

Cheers,
C

**Comment by Descolada** [comment]
This is the correct place to ask on GitHub. Unfortunately this is a UWP OCR "feature" which I have no control over. I figure it's because its main purpose is text recognition, and single characters don't classify as text.
