### ISSUE TITLE
Result.ControlClick is not working.

### ISSUE THREAD

**Issue by lawkaita** [Descolada/OCR#5]
### Steps to reproduce
```ahk
wt := "title"
buttext := "click me"

g := gui(unset, wt)
g.add('button', 'default', buttext).onEvent('click', (*) => g.Destroy())
g.marginx := 200
g.show()
sleep 100

result := OCR.fromWindow(wt)
obj := result.findString(buttext)
result.controlclick(obj)
```
### Expected behaviour
The gui `g` is destroyed.
### Actual behaviour
Nothing.

### Demonstration of built-in ControlClick working
```ahk
wt := "title"
buttext := "click me"

g := gui(unset, wt)
g.add('button', 'default', buttext).onEvent('click', (*) => g.Destroy())
g.marginx := 200
g.show()
sleep 100

x := 35
y := 20
controlClick("x" x " y" y, wt)
```
### Further investigation
The final x and y values passed to the built-in `ControlClick` at the end of `Result.ControlClick` seem strange.
Modifying the `Result.ControlClick` function by adding the line
```ahk
        MsgBox("X" (x+w//2) " Y" (y+h//2))
```
before the [final call](https://github.com/Descolada/OCR/blob/34d2b2132d477884b5c69a5cce82a16bae0d4c2b/Lib/OCR.ahk#L255) to the built-in `ControlClick` shows `X11 Y-27` in the "Steps to reproduce" example.

**Comment by Descolada** [comment]
Thanks for the report, should be fixed now.
